#application.yml
spring:
  application:
    name: ${APP_NAME:unnamed}
  #数据连接池配置信息
  datasource:
    url: jdbc:mysql://121.4.179.240:3306/emergencyguide?serverTimezone=GMT%2B8
    username: root
    password: RMTouHou.18
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        timeout: 1000
server:
  #服务器部署端口
  port: 8096
mybatis:
  type-aliases-package: com.emergencyguide.Entity
  mapper-locations: classpath:com/emergencyguide/Dao/Mapper/System/*.xml,
                    classpath:com/emergencyguide/Dao/Mapper/EmergencyInformation/*.xml,
                    classpath:com/emergencyguide/Dao/Mapper/Logo/*.xml,
                    classpath:com/emergencyguide/Dao/Mapper/Community/*.xml,
                    classpath:com/emergencyguide/Dao/Mapper/Product/*.xml,
                    classpath:com/emergencyguide/Dao/Mapper/*.xml

  config-location: classpath:mybatis-config.xml